app_name: "Kindsalabim Events"
company_name: "Kindsalabim Kinderevents"
company_address: "Charlottenweg 55, 45289 Essen"
company_email: "info@kindsalabim.de"
company_phone: "0177/7442137"
primary_color: "#166534"

smtp_host: "secure.emailsrvr.com"
smtp_port: 465
smtp_user: "info@kindsalabim.de"
smtp_password: "!819gtIt&Owc6TPg-+"
smtp_from: "info@kindsalabim.de"

cron_secret: "ks-cron-2026"
admin_email: "a.malca@kindsalabim.de"
admin_password_hash: "$2b$12$qbYxmQYGFjfKPO5v9pVZxOWarR9JwypoTtDYNqgCtZtC65X75mCi6"
secret_key: "cbc98c08464b3ed76ac7e0acf2804bf38da3464f909872b4b7c45595c199da20"
